# -*- coding: utf-8 -*-
"""Tugas Pekan 11 - NLP - Machine Translation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hwv3L-jDmNr1Iec-bmQzRyXuGlwtDUsp

# **Machine Translation**

Indonesia - Sunda

---

Clarisa Hasya Y - 1301174256
"""

import nltk
from nltk.translate import Alignment, AlignedSent
from nltk.translate import IBMModel1

"""Definisi korpus paralel yang berisi alignment"""

corpus =[]
corpus.append(AlignedSent( ["saya", "mau", "makan" ], \
            ["abdi", "hoyong", "tuang" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["rumah", "ini", "kecil" ], \
            ["imah", "ieu", "leutik" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["rumah", "itu", "besar" ], \
            ["imah", "éta", "ageung" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["mobil", "itu", "besar" ], \
            ["mobil", "éta", "ageung" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["saya", "mau", "minum" ], \
            ["abdi", "hoyong", "nginum" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))

corpus.append(AlignedSent( ["ibu", "pergi", "ke", "pasar" ], \
            ["ibu", "angkat", "ka", "pasar" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2), (3 , 3) ] ) ))
corpus.append(AlignedSent( ["ayah", "sedang", "memasak" ], \
            ["bapa", "nuju", "masak" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["sarah", "sedang", "makan" ], \
            ["sarah", "nuju", "tuang" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["saya", "sedang", "berenang" ], \
            ["abdi", "nuju", "ngojay" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["saya", "mengambil", "uang" ], \
            ["abdi", "nyandak", "artos" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))

corpus.append(AlignedSent( ["asep", "pergi", "ke", "sekolah" ], \
            ["asep", "angkat", "ka", "sakola" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2), (3 , 3) ] ) ))
corpus.append(AlignedSent( ["nisa", "memegang", "ikan" ], \
            ["nisa", "nyepeng", "lauk" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["tika", "membeli", "celana" ], \
            ["tika", "mésér", "calana" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["saya", "memegang", "ular" ], \
            ["abdi", "nyepeng", "oray" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["asep", "membuang", "sampah" ], \
            ["asep", "miceun", "runtah" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))

corpus.append(AlignedSent( ["nisa", "membeli", "baju" ], \
            ["nisa", "mésér", "acuk" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["saya", "melihat", "kucing" ], \
            ["abdi", "ningali", "ucing" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["ayah", "membuat", "kursi" ], \
            ["bapa", "ngadamel", "korsi" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["ibu", "membuat", "tumpeng" ], \
            ["ibu", "ngadamel", "tumpeng" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
corpus.append(AlignedSent( ["baju", "ini", "bagus" ], \
            ["acuk", "ieu", "saé" ] , \
            Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))

"""Pelatihan dengan iterasi sejumlah 100"""

com_ibm1 = IBMModel1(corpus, 100)

print(round(com_ibm1.translation_table["saya"]["abdi"], 3) )

print(round(com_ibm1.translation_table["kecil"]["leutik"], 3) )

print(round(com_ibm1.translation_table["besar"]["ageung"], 3) )

print(round(com_ibm1.translation_table["itu"]["ageung"], 3) )

print(round(com_ibm1.translation_table["ini"]["ieu"], 3) )

print(round(com_ibm1.translation_table["itu"]["éta"], 3) )

print(round(com_ibm1.translation_table["baju"]["acuk"], 3) )

print(round(com_ibm1.translation_table["sampah"]["runtah"], 3) )

print(round(com_ibm1.translation_table["membuang"]["miceun"], 3) )

corpus[14].invert()